### ISSUE TITLE
exposed port issue with docker module

### ISSUE THREAD

**Issue by spham** [ansible-community/molecule-docker#130] opened 2021-12-18 09:23 UTC
# Issue Type

exposed port not work

```
platforms:
  - name: instance
    image: docker.io/pycontribs/centos:7
    exposed_ports:
      - "80:80"
      - "8000:8000"
    published_ports:
      - "80:80"
      - "8000:8000"
```

- Bug report

# Molecule and Ansible details

```
ansible --version && molecule --version
```

Molecule installation method (one of):

python3 -m pip install molecule ansible-core
python3 -m pip install molecule-goss
python3 -m pip install molecule-docker

Ansible installation method (one of):

```
molecule --version

molecule 3.5.2 using python 3.9 
    ansible:2.11.6
    delegated:3.5.2 from molecule
    docker:1.1.0 from molecule_docker requiring collections: community.docker>=1.9.1
    hetznercloud:1.3.0 from molecule_hetznercloud
    vagrant:0.6.3 from molecule_vagrant
```

Detail any linters or test runners used:

```
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: docker.io/pycontribs/centos:7
    exposed_ports:
      - "8000:8000"
    published_ports:
      - "80:80"
      - "8000:8000"
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: goss
```

# Desired Behavior

I wish reach port from outside container

# Actual Behaviour

Connection refused

  curl -I 127.0.0.1:8000
  curl: (7) Failed to connect to 127.0.0.1 port 8000: Connexion refusée

**Comment by zhan9san** [comment] 2022-04-02 08:09
Hi @spham 
This issue can not be reproduced in latest version

```shell
molecule==3.6.1
molecule-docker==1.1.0
```

```shell
$ docker ps
CONTAINER ID   IMAGE                                          COMMAND                  CREATED         STATUS         PORTS                                               NAMES
f119fab110b2   molecule_local/docker.io/pycontribs/centos:7   "bash -c 'while true…"   6 minutes ago   Up 6 minutes   0.0.0.0:80->80/tcp, 0/tcp, 0.0.0.0:8000->8000/tcp   foo
```

Could you please have a try?

**Comment by ssbarnea** [comment] 2022-07-18 10:40
Closing as wont fix due to https://github.com/ansible-community/molecule-docker/discussions/85 so people would not imagine that bugs or features would magically be fixed by someone else. If you want to help, pull requests are likely the best way, start with simple ones.

**Closed by ssbarnea** 2022-07-18 10:40 UTC
