### ISSUE TITLE
molecule 3.1.x: unexpected keyword argument 'config_dict'

### ISSUE THREAD

**Issue by smutel** [ansible-community/molecule-docker#12] opened 2020-10-19 12:24 UTC
Hello,

When I use the last version of molecule and molecule-docker, I have this error message:
```
Traceback (most recent call last):
  File "/home/smu-dw/.local/share/virtualenvs/dw-users-ng-Vfczg4T7/bin/molecule", line 8, in <module>
    sys.exit(main())
  File "/home/smu-dw/.local/share/virtualenvs/dw-users-ng-Vfczg4T7/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/smu-dw/.local/share/virtualenvs/dw-users-ng-Vfczg4T7/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/smu-dw/.local/share/virtualenvs/dw-users-ng-Vfczg4T7/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/smu-dw/.local/share/virtualenvs/dw-users-ng-Vfczg4T7/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/smu-dw/.local/share/virtualenvs/dw-users-ng-Vfczg4T7/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/smu-dw/.local/share/virtualenvs/dw-users-ng-Vfczg4T7/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/smu-dw/.local/share/virtualenvs/dw-users-ng-Vfczg4T7/lib/python3.8/site-packages/molecule/command/check.py", line 111, in check
    base.execute_cmdline_scenarios(scenario_name, args, command_args)
  File "/home/smu-dw/.local/share/virtualenvs/dw-users-ng-Vfczg4T7/lib/python3.8/site-packages/molecule/command/base.py", line 104, in execute_cmdline_scenarios
    execute_scenario(scenario)
  File "/home/smu-dw/.local/share/virtualenvs/dw-users-ng-Vfczg4T7/lib/python3.8/site-packages/molecule/command/base.py", line 146, in execute_scenario
    execute_subcommand(scenario.config, action)
  File "/home/smu-dw/.local/share/virtualenvs/dw-users-ng-Vfczg4T7/lib/python3.8/site-packages/molecule/command/base.py", line 135, in execute_subcommand
    return command(config).execute()
  File "/home/smu-dw/.local/share/virtualenvs/dw-users-ng-Vfczg4T7/lib/python3.8/site-packages/molecule/command/destroy.py", line 108, in execute
    self._config.provisioner.destroy()
  File "/home/smu-dw/.local/share/virtualenvs/dw-users-ng-Vfczg4T7/lib/python3.8/site-packages/molecule/provisioner/ansible.py", line 702, in destroy
    pb.execute()
  File "/home/smu-dw/.local/share/virtualenvs/dw-users-ng-Vfczg4T7/lib/python3.8/site-packages/molecule/provisioner/ansible_playbook.py", line 104, in execute
    self._config.driver.sanity_checks()
  File "/home/smu-dw/.local/share/virtualenvs/dw-users-ng-Vfczg4T7/lib/python3.8/site-packages/molecule_docker/driver.py", line 234, in sanity_checks
    docker_client = docker.from_env()
  File "/home/smu-dw/.local/share/virtualenvs/dw-users-ng-Vfczg4T7/lib/python3.8/site-packages/docker/client.py", line 84, in from_env
    return cls(
  File "/home/smu-dw/.local/share/virtualenvs/dw-users-ng-Vfczg4T7/lib/python3.8/site-packages/docker/client.py", line 40, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/home/smu-dw/.local/share/virtualenvs/dw-users-ng-Vfczg4T7/lib/python3.8/site-packages/docker/api/client.py", line 125, in __init__
    self._auth_configs = auth.load_config(
TypeError: load_config() got an unexpected keyword argument 'config_dict'
```

Perhaps something in my configuration is no longer working with this new version ... ?
But what item ?

**Comment by ssbarnea** [comment] 2020-10-21 16:45
Please provide a way to reproduce the problem, or even better a PR with a fix. Without this I doubt anyone would step in and fix it.

**Comment by Nightreaver** [comment] 2020-10-23 10:28
Hello

I am experiencing the same issue. Whenever we build ansible since last Friday(?) the molecule will fail with that exact issue.
It seems that its currently not possible to install a new molecule-docker that will not fail.

IMHO this is nothing that ca be ignored

**Comment by ssbarnea** [comment] 2020-10-23 12:02
Posting a stacktrace is usually not enough in order to identify a bug. We need a way to reproduce it and none of you mentioned this. I would be happy to help, but I cannot do it without enough information.

**Comment by Nightreaver** [comment] 2020-10-23 12:18
Figured out the bug probably.

In the "official" molecule Dockerfile https://github.com/ansible-community/molecule/blob/master/Dockerfile they install both, `docker` and `docker-py`. These packages incompatible. Installing either on top of the other will break molecule docker. installing either of them seperately seem to work fine.

So make sure you dont install "docker-py" at any point, but rather the proper `docker` module. Then issue should go away.

**Comment by ssbarnea** [comment] 2020-10-23 16:32
@Nightreaver You have the opportunity to make PR to molecule with a simple fix to Dockerfile.

**Comment by tadeboro** [comment] 2021-05-16 20:39
Closing as molecule does not provide a Dockerfile anymore.

**Closed by tadeboro** 2021-05-16 20:39 UTC
Labels: bug
